import { MessageNotificationProvider } from "./context/MessageNotificartion/MessageNotificationContext";
import ReactQueryProvider from "./components/ReactQueryProvider/ReactQueryProvider";
import { CartProvider } from "./context/CartContext/CartContext";
import DialogContext from "./context/CustomDialog/DialogContext";
import { UserProvider } from "./context/CurrentUser/CurrentUser";
import { Geist, Geist_Mono } from "next/font/google";
import Footer from "./components/Footer/Footer";
import type { Metadata } from "next";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Xivia Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const isDarkmode: boolean = false;
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ReactQueryProvider>
          <UserProvider>
            <MessageNotificationProvider>
              <DialogContext>
                <CartProvider>
                  {/* <Navbar /> */}
                  {children}
                  <Footer />
                </CartProvider>
              </DialogContext>
            </MessageNotificationProvider>
          </UserProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
