import { CartProvider } from "./context/CartContext/CartContext";
import { Geist, Geist_Mono } from "next/font/google";
// import Navbar from "./components/common/Navbar/Navbar";
import type { Metadata } from "next";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Xivia Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <CartProvider>
          {/* <Navbar /> */}
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
