import { CartProvider } from "./context/CartContext/CartContext";
import DialogContext from "./context/CustomDialog/DialogContext";
import { Geist, Geist_Mono } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Xivia Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isDarkmode: boolean = false;
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <DialogContext>
          <CartProvider>
            {/* <Navbar /> */}
            {children}
          </CartProvider>
        </DialogContext>
      </body>
    </html>
  );
}
